server:
  port: 8080

spring:
  application:
    name: zj-admin-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

